version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - STATS-SERVER-URL=http://stats-server:9090
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_NAME=stats
      - DB_HOST=stats_db
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    container_name: stats-db
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    hostname: stats_db

  ewm-service:
    build: ewm
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS-SERVER-URL=http://stats-server:9090
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_NAME=ewm
      - DB_HOST=ewm_db
      - DB_PORT=5432

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    hostname: ewm_db
