drop table if exists stats;

create table if not exists stats (
    id bigint generated by default as identity,
    app varchar not null,
    uri varchar not null,
    ip varchar not null,
    timestamp timestamp not null,
    constraint PK_STATS primary key (id)
);